// <auto-generated>
// This file is generated by AppUIBindingGenerator. Do not edit by hand.
// </auto-generated>
using UnityEngine;

namespace Joi.H.AppUI.Samples.TextMeshPro
{
    public partial class TextMeshProSamplePageController
    {
        [SerializeField]
        private TMPro.TMP_Text m_TitleTextTxt;

        protected TMPro.TMP_Text TitleTextTxt
        {
            get { return m_TitleTextTxt; }
        }

        [SerializeField]
        private TMPro.TMP_InputField m_NameInputInput;

        protected TMPro.TMP_InputField NameInputInput
        {
            get { return m_NameInputInput; }
        }

        [SerializeField]
        private TMPro.TMP_Dropdown m_OptionsDropdownDropdown;

        protected TMPro.TMP_Dropdown OptionsDropdownDropdown
        {
            get { return m_OptionsDropdownDropdown; }
        }

        [SerializeField]
        private UnityEngine.UI.Button m_FirstButtonBtn;

        protected UnityEngine.UI.Button FirstButtonBtn
        {
            get { return m_FirstButtonBtn; }
        }

        [SerializeField]
        private UnityEngine.UI.Button m_SecondButtonBtn;

        protected UnityEngine.UI.Button SecondButtonBtn
        {
            get { return m_SecondButtonBtn; }
        }

        #if UNITY_EDITOR
        protected override void ValidateBindingsEditorEx(Joi.H.AppUI.UIBindingValidationResult result)
        {
            base.ValidateBindingsEditorEx(result);
            ValidateRequiredBinding(result, "TitleTextTxt", m_TitleTextTxt, "TMPro.TMP_Text");
            ValidateRequiredBinding(result, "NameInputInput", m_NameInputInput, "TMPro.TMP_InputField");
            ValidateRequiredBinding(result, "OptionsDropdownDropdown", m_OptionsDropdownDropdown, "TMPro.TMP_Dropdown");
            ValidateRequiredBinding(result, "FirstButtonBtn", m_FirstButtonBtn, "UnityEngine.UI.Button");
            ValidateRequiredBinding(result, "SecondButtonBtn", m_SecondButtonBtn, "UnityEngine.UI.Button");
        }
        #endif
    }
}
