using System.Text;

namespace Joi.H.AppUI.Editor.Binding
{
    /// <summary>
    /// 根据扫描结果生成 partial .Bindings.cs 文本。
    /// 只负责拼接代码字符串，不访问磁盘，因此可以被生成器和只读校验安全复用。
    /// </summary>
    public static class UIBindingCodeWriter
    {
        /// <summary>
        /// 生成包含序列化字段、只读属性和 Editor 绑定校验方法的 C# 源码。
        /// </summary>
        public static string Write(UIBindingSourceInfo sourceInfo, UIBindingScanResult scanResult)
        {
            StringBuilder builder = new StringBuilder(2048);
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This file is generated by AppUIBindingGenerator. Do not edit by hand.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(sourceInfo.NamespaceName);
            if (hasNamespace)
            {
                builder.Append("namespace ").AppendLine(sourceInfo.NamespaceName);
                builder.AppendLine("{");
            }

            string indent = hasNamespace ? "    " : string.Empty;
            builder.Append(indent).Append("public partial class ").Append(sourceInfo.TypeName).AppendLine();
            builder.Append(indent).AppendLine("{");

            WriteFields(builder, indent + "    ", scanResult);
            WriteValidation(builder, indent + "    ", scanResult);

            builder.Append(indent).AppendLine("}");
            if (hasNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        /// <summary>
        /// 为每个绑定目标生成 private SerializeField 字段和 protected 访问属性。
        /// </summary>
        private static void WriteFields(
            StringBuilder builder,
            string indent,
            UIBindingScanResult scanResult)
        {
            for (int i = 0; i < scanResult.Bindings.Count; i++)
            {
                UIBindingInfo binding = scanResult.Bindings[i];
                builder.Append(indent).Append("[SerializeField]").AppendLine();
                builder.Append(indent)
                    .Append("private ")
                    .Append(binding.CodeTypeName)
                    .Append(' ')
                    .Append(binding.FieldName)
                    .Append(';')
                    .AppendLine();
                builder.AppendLine();
                builder.Append(indent)
                    .Append("protected ")
                    .Append(binding.CodeTypeName)
                    .Append(' ')
                    .Append(binding.PropertyName)
                    .AppendLine();
                builder.Append(indent).AppendLine("{");
                builder.Append(indent).Append("    get { return ").Append(binding.FieldName).AppendLine("; }");
                builder.Append(indent).AppendLine("}");
                builder.AppendLine();
            }
        }

        /// <summary>
        /// 写入 Editor-only 的绑定缺失校验，让运行时代码不携带额外验证成本。
        /// </summary>
        private static void WriteValidation(
            StringBuilder builder,
            string indent,
            UIBindingScanResult scanResult)
        {
            builder.Append(indent).AppendLine("#if UNITY_EDITOR");
            builder.Append(indent).AppendLine("protected override void ValidateBindingsEditorEx(Joi.H.AppUI.UIBindingValidationResult result)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    base.ValidateBindingsEditorEx(result);");
            for (int i = 0; i < scanResult.Bindings.Count; i++)
            {
                UIBindingInfo binding = scanResult.Bindings[i];
                builder.Append(indent)
                    .Append("    ValidateRequiredBinding(result, \"")
                    .Append(binding.PropertyName)
                    .Append("\", ")
                    .Append(binding.FieldName)
                    .Append(", \"")
                    .Append(binding.CodeTypeName)
                    .AppendLine("\");");
            }

            builder.Append(indent).AppendLine("}");
            builder.Append(indent).AppendLine("#endif");
        }
    }
}
