using System;
using System.IO;
using System.Text.RegularExpressions;
using Joi.H.AppUI;
using UnityEditor;
using UnityEditor.Compilation;

namespace Joi.H.AppUI.Editor.Binding
{
    /// <summary>
    /// 绑定生成文件相关的路径、覆盖保护和编译边界校验工具。
    /// </summary>
    public static class UIBindingFileUtility
    {
        /// <summary>
        /// 自动生成文件标记。覆盖保护依赖该标记，防止误覆盖手写文件。
        /// </summary>
        public const string AutoGeneratedMarker = "<auto-generated>";

        /// <summary>
        /// 从当前 Controller 解析脚本路径、命名空间和生成文件路径。
        /// Controller 必须是顶层 partial class，确保生成的 partial 文件可以正常合并。
        /// </summary>
        public static bool TryGetSourceInfo(
            UIBindingScopeBase scope,
            out UIBindingSourceInfo info,
            out string error)
        {
            info = default(UIBindingSourceInfo);
            error = string.Empty;

            if (scope == null)
            {
                error = "Binding scope is null.";
                return false;
            }

            MonoScript script = MonoScript.FromMonoBehaviour(scope);
            if (script == null)
            {
                error = "Cannot locate controller script.";
                return false;
            }

            string scriptPath = AssetDatabase.GetAssetPath(script);
            if (string.IsNullOrEmpty(scriptPath) || !File.Exists(scriptPath))
            {
                error = "Controller script path is invalid.";
                return false;
            }

            string source = File.ReadAllText(scriptPath);
            System.Type type = scope.GetType();
            string escapedTypeName = Regex.Escape(type.Name);
            bool isPartial = Regex.IsMatch(
                source,
                "\\bpartial\\s+class\\s+" + escapedTypeName + "\\b");
            if (!isPartial)
            {
                error = "Controller must be declared as partial class: " + type.Name;
                return false;
            }

            if (type.IsGenericType || type.IsNested)
            {
                error = "Controller must be a top-level non-generic type.";
                return false;
            }

            string namespaceName = string.Empty;
            Match namespaceMatch = Regex.Match(
                source,
                "\\bnamespace\\s+([A-Za-z_][A-Za-z0-9_\\.]*)");
            if (namespaceMatch.Success)
            {
                namespaceName = namespaceMatch.Groups[1].Value;
            }

            string directory = Path.GetDirectoryName(scriptPath);
            string generatedPath = Path.Combine(directory, type.Name + ".Bindings.cs")
                .Replace('\\', '/');

            info = new UIBindingSourceInfo(
                type.Name,
                namespaceName,
                scriptPath,
                generatedPath);
            return true;
        }

        /// <summary>
        /// 判断目标 .Bindings.cs 是否可以被覆盖。
        /// 缺失文件或带 auto-generated 标记的文件可覆盖，手写文件一律阻止。
        /// </summary>
        public static bool CanOverwriteGeneratedFile(string path, out string error)
        {
            error = string.Empty;
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
            {
                return true;
            }

            string content = File.ReadAllText(path);
            if (content.Contains(AutoGeneratedMarker))
            {
                return true;
            }

            error = "Bindings file exists but is not marked as auto-generated: " + path;
            return false;
        }

        /// <summary>
        /// 校验 Controller 脚本和生成文件是否位于同一 Unity 编译边界。
        /// 优先比较 assembly name，取不到时回退到 asmdef 路径，默认编译域用 null/null 视为一致。
        /// </summary>
        public static bool TryValidateCompilationBoundary(
            UIBindingSourceInfo info,
            out string error)
        {
            error = string.Empty;
            string scriptPath = NormalizeAssetPath(info.ScriptPath);
            string generatedPath = NormalizeAssetPath(info.GeneratedPath);
            if (string.IsNullOrEmpty(scriptPath) || string.IsNullOrEmpty(generatedPath))
            {
                error = "Cannot validate binding compilation boundary: source paths are invalid.";
                return false;
            }

            string scriptAssembly;
            string generatedAssembly;
            string scriptAsmdef;
            string generatedAsmdef;
            try
            {
                scriptAssembly = CompilationPipeline.GetAssemblyNameFromScriptPath(scriptPath);
                generatedAssembly = CompilationPipeline.GetAssemblyNameFromScriptPath(generatedPath);
                scriptAsmdef = NormalizeAssetPath(
                    CompilationPipeline.GetAssemblyDefinitionFilePathFromScriptPath(scriptPath));
                generatedAsmdef = NormalizeAssetPath(
                    CompilationPipeline.GetAssemblyDefinitionFilePathFromScriptPath(generatedPath));
            }
            catch (Exception exception)
            {
                error = "Failed to validate binding compilation boundary: " + exception.Message;
                return false;
            }

            if (!string.IsNullOrEmpty(scriptAssembly) && !string.IsNullOrEmpty(generatedAssembly))
            {
                // assembly name 可用时最准确，直接用 Unity 编译管线给出的结果判断。
                if (string.Equals(scriptAssembly, generatedAssembly, StringComparison.Ordinal))
                {
                    return true;
                }

                error = BuildCompilationBoundaryError(
                    scriptPath,
                    generatedPath,
                    scriptAssembly,
                    generatedAssembly);
                return false;
            }

            if (string.Equals(scriptAsmdef, generatedAsmdef, StringComparison.Ordinal))
            {
                // 默认 Assembly-CSharp 场景下两个 asmdef 路径都为空，也会落入这里通过。
                return true;
            }

            error = BuildCompilationBoundaryError(
                scriptPath,
                generatedPath,
                FormatBoundary(scriptAssembly, scriptAsmdef),
                FormatBoundary(generatedAssembly, generatedAsmdef));
            return false;
        }

        /// <summary>
        /// 统一路径分隔符，避免 Windows 反斜杠影响 Unity Asset 路径比较。
        /// </summary>
        private static string NormalizeAssetPath(string path)
        {
            return string.IsNullOrEmpty(path) ? string.Empty : path.Replace('\\', '/');
        }

        /// <summary>
        /// 将编译边界信息格式化为可读文本，便于错误日志定位。
        /// </summary>
        private static string FormatBoundary(string assemblyName, string asmdefPath)
        {
            if (!string.IsNullOrEmpty(assemblyName))
            {
                return assemblyName;
            }

            if (!string.IsNullOrEmpty(asmdefPath))
            {
                return asmdefPath;
            }

            return "<default Unity assembly>";
        }

        /// <summary>
        /// 构造带路径和边界信息的错误文本。
        /// </summary>
        private static string BuildCompilationBoundaryError(
            string scriptPath,
            string generatedPath,
            string scriptBoundary,
            string generatedBoundary)
        {
            return
                "Controller and generated Bindings file are in different compilation boundaries. " +
                "Controller: " + scriptPath +
                " [" + scriptBoundary + "], Bindings: " + generatedPath +
                " [" + generatedBoundary + "].";
        }
    }

    /// <summary>
    /// 描述一次绑定生成需要的源脚本信息与目标生成路径。
    /// </summary>
    public readonly struct UIBindingSourceInfo
    {
        /// <summary>
        /// Controller 类型名，也是生成 partial class 的类名。
        /// </summary>
        public readonly string TypeName;

        /// <summary>
        /// Controller 所在命名空间；为空表示全局命名空间。
        /// </summary>
        public readonly string NamespaceName;

        /// <summary>
        /// 手写 Controller 脚本 Asset 路径。
        /// </summary>
        public readonly string ScriptPath;

        /// <summary>
        /// 自动生成 .Bindings.cs 的 Asset 路径。
        /// </summary>
        public readonly string GeneratedPath;

        /// <summary>
        /// 创建源信息快照；空值统一转为空字符串，减少调用方判空分支。
        /// </summary>
        public UIBindingSourceInfo(
            string typeName,
            string namespaceName,
            string scriptPath,
            string generatedPath)
        {
            TypeName = typeName ?? string.Empty;
            NamespaceName = namespaceName ?? string.Empty;
            ScriptPath = scriptPath ?? string.Empty;
            GeneratedPath = generatedPath ?? string.Empty;
        }
    }
}
